
#' Calculate Distribution of Complexities by Isolate
#'
#' @description This function will calculate the distribution of
#' susceptibilities by isolate.
#' @inheritParams summarize_rps
#' @seealso [plot.hagis.complexities()]
#' @importFrom data.table ":="
#' @examples
#'
#' # locate system file for import
#' Ps <- system.file("extdata", "practice_data_set.csv", package = "hagis")
#'
#' # import 'practice_data_set.csv'
#' Ps <- read.csv(Ps)
#' head(Ps)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#'complexities <- calculate_complexities(x = Ps,
#'                                       cutoff = 60,
#'                                       control = "susceptible",
#'                                       sample = "Isolate",
#'                                       Rps = "Rps",
#'                                       perc_susc = "perc.susc")
#' complexities
#' summary(complexities)
#'
#' @return `calculate_complexities` returns an object of class
#' `hagis.complexities`.
#' 
#' An object of class `hagis.complexities` is a `list` containing the following
#'  components
#'   \itemize{
#'     \item{grouped_complexities} {a [data.table][data.table()] object of
#'       grouped complexities}
#'     \item{individual_complexities} {a [data.table][data.table()] object of
#'       individual complexities}
#'   }
#' @export calculate_complexities
 
calculate_complexities = function(x,
                                  cutoff,
                                  control,
                                  sample,
                                  Rps,
                                  perc_susc) {
  # CRAN NOTE avoidance
  N_samp <- NULL
  
    if (missing(x) |
      missing(cutoff) |
      missing(control) |
      missing(sample) |
      missing(Rps) |
      missing(perc_susc)) {
    stop(call. = FALSE,
         "You have failed to provide all necessary inputs.\
         Please check and try again.")
  }
  
  data.table::setDT(x)
  # The susceptible control is removed from all isolates in the data set so that
  #  it will not affect complexity calculations and a new data set is made that
  #  it does not contain susceptible controls.
  
  x <- subset(x, Rps != control)
  x[, Rps := droplevels(Rps)]
  
  # summarise the reactions, create susceptible.1 field, see
  # internal_functions.R
  x <- .binary_cutoff(.x = x, .cutoff = cutoff)
  
  # set the sample field to factor
  expr <- paste0("x[, ", sample, ":= as.factor(", sample, ")]")
  eval(parse(text = expr))
  
  # Individual isolate complexities as calculated by grouping by "sample" and
  # then summarising the number of "1"s for each "sample" in the "susceptible.1"
  # field, see internal_functions.R
  individual_complexities <-
    .create_summary_isolate(.y = x, .sample = sample)
  
  # Frequency for each complexity (%).
  # Percent frequency is calculated by taking the individual complexity of each
  # Isolate and grouping all Isolates by their complexity
  
  
  # create an object of the number of genes in the data
  expr <- paste0("x[, ", Rps, "]")
  n_gene <- length(unique(eval(parse(text = expr))))
  
  # create an object of the number of samples in the data
  expr <- paste0("x[, ", sample, "]")
  n_sample <- length(unique(eval(parse(text = expr))))
  
  # create an empty list to populate with frequency values
  complexities <- vector(mode = "list", length = n_gene)
  names(complexities) <- seq_along(1:n_gene)
  
  for (i in seq_along(1:n_gene)) {
    complexities[[i]] <- round(length(which(
      individual_complexities[, N_samp == i])) / n_sample * 100, 2)
  }
  
  grouped_complexities <- data.table::setDT(stack(complexities))
  names(grouped_complexities) <- c("frequency", "N_samp")
  
  # distribution of complexity (counts)
  dist <- individual_complexities[, .N, by = N_samp]
  dist[, N_samp := as.factor(N_samp)]
  grouped_complexities[dist, on = "N_samp", distribution := i.N]
  
  # set NA to 0 for distribution
  grouped_complexities[is.na(distribution), distribution := 0]
  data.table::setcolorder(grouped_complexities,
                          neworder = c("N_samp", "frequency", "distribution"))
  data.table::setnames(grouped_complexities,
                       c("complexity", "frequency", "distribution"))
  complexities <-
    list(grouped_complexities, individual_complexities)
  names(complexities) <-
    c("grouped_complexities", "indvidual_complexities")
  
  # Set new class
  class(complexities) <- union("hagis.complexities", class(x))
  
  return(complexities)
}

#' Plot \pkg{hagis} Complexities
#'
#' @description Creates a \pkg{ggplot2} object of the frequency of complexity
#'  (% per complexity) calculated by [calculate_complexities()] or a
#'  \pkg{ggplot2} object of the distribution (number per complexity).
#' @param object a \pkg{hagis} `complexities` object generated by
#'  [calculate_complexities()]. Character.
#' @param y a vector of values for which the bar plot is desired. Specify
#'  whether to return a graph of the frequency of complexities as a percentage,
#'  "`frequency`", or as the count, "`distribution`". Character.
#'
#' @examples
#  # locate system file for import
#' Ps <- system.file("extdata", "practice_data_set.csv", package = "hagis")
#'
#' # import 'practice_data_set.csv'
#' Ps <- read.csv(Ps)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#'complexities <- calculate_complexities(x = Ps,
#'                                       cutoff = 60,
#'                                       control = "susceptible",
#'                                       sample = "Isolate",
#'                                       Rps = "Rps",
#'                                       perc_susc = "perc.susc")
#'
#' # Visualize the distribution (actual values)
#' plot(object = complexities, y = "distribution")
#' 
#' # Visualize the frequency (percentages)
#' plot(object = complexities, y = "frequency")
#' 
#' @return A \link[ggplot2]{ggplot2} plot
#' @seealso [calculate_complexities()]
#' @export plot.hagis.complexities

plot.hagis.complexities <- function(object, y, ...) {
  # create a single data.frame to use in the ggplot call
  z <- object[[1]]
  
  plot_frequency <- function(.data) {
    #CRAN Note avoidance
    complexity <- frequency <- NULL
    ggplot2::ggplot(data = .data,
                    ggplot2::aes(x = complexity,
                                 y = frequency)) +
      ggplot2::geom_col() +
      ggplot2::scale_y_continuous(name = "Percent of Isolates") +
      ggplot2::ggtitle("Percentage of Pathotype Complexities") +
      ggplot2::coord_flip()
  }
  
  plot_distribution <- function(.data) {
    #CRAN Note avoidance
    complexity <- distribution <- NULL
      ggplot2::ggplot(data = .data,
                      ggplot2::aes(x = complexity,
                                   y = distribution)) +
      ggplot2::geom_col() +
      ggplot2::scale_y_continuous(name = "Number of Isolates") +
      ggplot2::ggtitle("Number of Isolates in Each Pathotype Complexity") +
      ggplot2::coord_flip()
  }
  
  if (y == "frequency") {
    plot_frequency(.data = z)
  } else {
    plot_distribution(.data = z)
  }
}

#' Create Summary Table of Binary Reactions by Sample
#'
#' Tally a summary by sample or isolate. This code takes the "Susceptible.1"
#'  column and summarises it by gene for your total Isolates pathogenic on each
#'  sample.
#'
#' @param x A \pkg{hagis} `complexities` object generated by
#'  [calculate_complexities()]. Character.
#' @return A `data.table` that tallies the results by sample
#' @author Adam H. Sparks, adamhsparks@@gmail.com
#' @noRd
.create_summary_isolate <- function(.y, .sample) {
  expr = paste0(".y[, list(N_samp = sum(susceptible.1)), by = list(sample = ",
                .sample,
                ")]")
  y <- eval(parse(text = expr))
  return(y)
}


#' Summarises \pkg{hagis} Complexity Object
#'
#' Custom [summary()] method for \pkg{hagis} `complexities` objects.
#'
#' @param x A hagis class object (a list of two `data.table`s)
#' @param ... ignored
#' @noRd
summary.hagis.complexities <- function(object, ...) {
  mn <- mean(object$indvidual_complexities$N_samp)
  sd <- sd(object$indvidual_complexities$N_samp)
  se <- sqrt(
    var(object$indvidual_complexities$N_samp) /
      length(object$indvidual_complexities$N_samp)
  )
  
  x <- list(mn, sd, se)
  names(x) <- c("Mean", "sd", "se")
  class(x) <- "summary.complexity"
  x
}

#' Prints summary.hagis Object for Complexities
#'
#' Custom [print()] method for \pkg{hagis} `summary.complexity` objects.
#'
#' @param x a summary.hagis object
#' @param ... ignored
#' @noRd
print.summary.complexity <- function(x,
                                digits = max(3L, getOption("digits") - 3L),
                                ...) {
  cat("\nMean of Complexities\n")
  cat(x$Mean, "\n")
  cat("\nStandard Deviation of Complexities\n")
  cat(x$sd, "\n")
  cat("\nStandard Error of Complexities\n")
  cat(x$se)
  invisible(x)
}

#' Prints hagis.complexities Object
#'
#' Custom [print()] method for \pkg{hagis} `complexity` objects.
#'
#' @param x a hagis.complexities object
#' @param ... ignored
#' @noRd
print.hagis.complexities <- function(x,
                                digits = max(3L, getOption("digits") - 3L),
                                ...) {
  cat("\nGrouped Complexities\n")
  print(x[[1]])
  cat("\n")
  cat("\nIndividual Complexities\n")
  print(x[[2]])
  cat("\n")
  invisible(x)
}

