

plot.hagis.complexities <- function(x, type, color = NULL, order = NULL, ...) {
  print(autoplot(x, type, color, order, ...))
}

#' Create Summary Table of Binary Reactions by Sample
#'
#' Tally a summary by sample or isolate. This code takes the "Susceptible.1"
#'  column and summarises it by gene for your total Isolates pathogenic on each
#'  sample.
#'
#' @param x A \pkg{hagis} `complexities` object generated by
#'  [calculate_complexities()]. Character.
#' @return A `data.table` that tallies the results by sample
#' @noRd
#' @export
.create_summary_isolate <- function(.y) {
  susceptible.1 <- NULL
  .y <- .y[, list(N_samp = sum(susceptible.1)), by = list(sample)]
  return(.y)
}

