

#' Calculate Distribution of Complexities by Isolate
#'
#' @description This function will calculate the distribution of
#' susceptibilities by isolate.
#' @inheritParams summarize_rps
#' @seealso [visualize_distribution()], [visualize_complexity()]
#' @importFrom data.table ":="
#' @examples
#'
#' # locate system file for import
#' Ps <- system.file("extdata", "practice_data_set.csv", package = "hagis")
#'
#' # import 'practice_data_set.csv'
#' Ps <- read.csv(Ps)
#' head(Ps)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#' complexities <- calculate_complexities(x = Ps,
#'                        cutoff = 60,
#'                        control = "susceptible",
#'                        sample = "Isolate",
#'                        Rps,
#'                        perc_susc = "perc.susc")
#' complexities
#'
#' @export calculate_complexities

calculate_complexities = function(x,
                             cutoff,
                             control,
                             sample,
                             Rps,
                             perc_susc) {
  # CRAN NOTE avoidance
  Rps <- .N <- i.N <- N_samp <- NULL
  
  if (missing(x) |
      missing(cutoff) |
      missing(control) |
      missing(sample) |
      missing(Rps) |
      missing(perc_susc)) {
    stop(call. = FALSE,
         "You have failed to provide all necessary inputs.\
         Please check and try again.")
  }
  
  data.table::setDT(x)
  # The susceptible control is removed from all isolates in the data set so that
  #  it will not affect complexity calculations and a new data set is made that
  #  it does not contain susceptible controls.
  
  x <- subset(x, Rps != control)
  x[, Rps := droplevels(Rps)]
  
  # summarise the reactions, create susceptible.1 field, see
  # internal_functions.R
  x <- .binary_cutoff(.x = x, .cutoff = cutoff)
  
  # set the sample field to factor
  expr <- paste0("x[, ", sample, ":= as.factor(", sample, ")]")
  eval(parse(text = expr))
  
  # Individual isolate complexities as calculated by grouping by "sample" and
  # then summarising the number of "1"s for each "sample" in the "susceptible.1"
  # field, see internal_functions.R
  y <- .create_summary_isolate(.y = x, .sample = sample)
  
  # Frequency for each complexity (%).
  # Percent frequency is calculated by taking the individual complexity of each
  # Isolate and grouping all Isolates by their complexity
  
  
  # create an object of the number of genes in the data
  expr <- paste0("x[, ", Rps, "]")
  n_gene <- length(unique(eval(parse(text = expr))))
  
  # create an object of the number of samples in the data
  expr <- paste0("x[, ", sample, "]")
  n_sample <- length(unique(eval(parse(text = expr))))
  
  # create an empty list to populate with frequency values
  complexities <- vector(mode = "list", length = n_gene)
  names(complexities) <- seq_along(1:n_gene)
  
  for (i in seq_along(1:n_gene)) {
    complexities[[i]] <- round(length(which(y[, N_samp == i])) / n_sample * 100, 2)
  }
  
  complexities <- data.table::setDT(stack(complexities))
  names(complexities) <- c("frequency", "N_samp")
  
  # distribution of complexity (counts)
  dist <- y[, .N, by = N_samp]
  dist[, N_samp := as.factor(N_samp)]
  complexities[dist, on = "N_samp", distribution := i.N]
  
  # set NA to 0 for distribution
  complexities[is.na(distribution), distribution := 0]
  data.table::setcolorder(complexities,
                          neworder = c("N_samp", "frequency", "distribution"))
  data.table::setnames(complexities,
                       c("complexity", "frequency", "distribution"))
  
  return(complexities)
}

#' Visualize Complexities
#'
#' @description Creates a \pkg{ggplot2} object of the frequency of complexity
#'  (% per complexity) calculated by [calculate_complexities()]
#' @param x A `data.frame` generated by [calculate_complexities()]. Character.
#'
#' @examples
#  # locate system file for import
#' Ps <- system.file("extdata", "practice_data_set.csv", package = "hagis")
#'
#' # import 'practice_data_set.csv'
#' Ps <- read.csv(Ps)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#' susc <- calculate_complexities(x = Ps,
#'                           cutoff = 60,
#'                           control = "susceptible",
#'                           sample = "Isolate",
#'                           Rps = "Rps",
#'                           perc_susc = "perc.susc")
#'
#' # Visualize the distribution (actual values)
#' visualize_complexities(susc)
#'
#' @seealso [calculate_complexities()], [visualize_distribution()]
#' @export visualize_complexities

visualize_complexities <- function(x) {
  #CRAN Note avoidance
  complexity <- frequency <- NULL
  
  complexities_graph <-
    ggplot2::ggplot(data = x,
                    ggplot2::aes(x = complexity,
                                 y = frequency)) +
    ggplot2::geom_col() +
    ggplot2::scale_y_continuous(name = "Percent of Isolates") +
    ggplot2::ggtitle("Percentage of Pathotype Complexities") +
    ggplot2::coord_flip()
  
  return(complexities_graph)
}

#' Visualize Distribution of Complexities
#'
#' @description Creates a \pkg{ggplot2} object of the frequency of distribution
#'  of complexities (N per complexity) calculated by [calculate_complexities()]
#' @inheritParams visualize_complexities
#'
#' @examples
#  # locate system file for import
#' Ps <- system.file("extdata", "practice_data_set.csv", package = "hagis")
#'
#' # import 'practice_data_set.csv'
#' Ps <- read.csv(Ps)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#'susc <- calculate_complexities(x = Ps,
#'                          cutoff = 60,
#'                          control = "susceptible",
#'                          sample = "Isolate",
#'                          Rps = "Rps",
#'                          perc_susc = "perc.susc")
#'
#' # Visualize the distribution (N per complexity)
#' visualize_distribution(susc)
#'
#' @seealso [calculate_complexities()], [visualize_complexity()]
#' @export visualize_distribution
#'

visualize_distribution <- function(x) {
  #CRAN Note avoidance
  complexity <- distribution <- NULL
  
  distribution_graph <-
    ggplot2::ggplot(data = x,
                    ggplot2::aes(x = complexity,
                                 y = distribution)) +
    ggplot2::geom_col() +
    ggplot2::scale_y_continuous(name = "Number of Isolates") +
    ggplot2::ggtitle("Number of Isolates in Each Pathotype Complexity") +
    ggplot2::coord_flip()
  
  return(distribution_graph)
}

#
# #S3 object using "summary" here
# summarize_complexities <- function(x) {
#   comp_mean <- mean(Ind_complexities$N)
#   comp_sd <- sd(Ind_complexities$N)
#   comp_stderr <- std.error(Ind_complexities$N)
# }

#' Create Summary Table of Binary Reactions by Sample
#'
#' Tally a summary by sample or isolate. This code takes the "Susceptible.1"
#'  column and summarises it by gene for your total Isolates pathogenic on each
#'  sample.
#'
#' @param .x A `data.table` containing the values to be summarised
#' @return A `data.table` that tallies the results by sample
#' @author Adam H. Sparks, adamhsparks@@gmail.com
#' @noRd
.create_summary_isolate <- function(.y, .sample) {
  expr = paste0(".y[, list(N_samp = sum(susceptible.1)), by = list(sample = ",
                .sample,
                ")]")
  y <- eval(parse(text = expr))
  return(y)
}
