
#' Calculate Distribution of Susceptibilities by _Rps_ Gene
#'
#' @description This function will calculate the distribution of
#' susceptibilities by _Rps_ gene.
#' @param x A `data.frame` containing the data. See Details below for more.
#'  Character.
#' @param cutoff Value for percent susceptible cutoff. Integer.
#' @param control Value used to denote the susceptible control in the \var{Rps}
#'  field. Defaults to "susceptible". Character.
#'
#' @details
#' The `data.frame` object supplied must contain fields with the following
#'  names and contents where each line is a unique observation.
#'
#'  * isolate - Unique identifier for the isolate
#'  * Rps - _Rps_ gene(s) included in study
#'  * total - Total number of plants
#'  * hr - Number of plants with hypersensitive response to inoculation
#'  * lesion - Number of plants with lesion in response to inoculation
#'  * lesion_to_cotyledon - Number of plants with lesion to cotyledon
#'  in response to inoculation
#'  * dead - Number of plants dead in response to inoculation
#'  * total.resis - Total number of plants exhibiting resistant reaction to
#'   inoculation
#'  * total.susc - Total number of plants exhibiting susceptible reaction to
#'   inoculation
#'  * perc.resis - Percent of plants exhibiting resistant reaction to
#'   inoculation
#'  * perc.susc - Percent of plants exhibiting susceptible reaction to
#'   inoculation
#'
#' The use of [write_template()] and [calc_percents()] is encouraged to ensure
#'  that the input `data.frame`, \var{x}, used is properly formatted.
#'
#' @examples
#' 
#' 
#' # locate system file for import
#' Ps <- system.file("extdata", "practice_data_set.csv", package = "hagis")
#'
#' # import 'practice_data_set.csv'
#' Ps <- read.csv(Ps)
#' head(Ps)
#'
#' # calculate totals and percents for resistant and susceptible reactions
#' Ps <- calc_percents(Ps)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#' susc <- summarize_Rps(Ps, cutoff = 60)
#' susc
#'
#' @seealso [write_template()], [percents()], [visualize_Rps()]
#' @importFrom data.table ":="
#' @export summarize_Rps

summarize_Rps <- function(x,
                          cutoff,
                          control = "susceptible") {
  # CRAN NOTE avoidance
  isolate <- susceptible.1 <- cutoff <- percent.pathogenic <- NULL
  data.table::setDT(x)

  # if else for resistant or susceptible reaction. This will mark susceptible
  # reactions with a "1" in a new column labelled "Susceptible.1" to then be
  # used in later analysis.
  susceptible <- x$perc.susc >= 60
  x[, susceptible.1 := 0][susceptible, susceptible.1 := 1]
  
  # summary by rps gene to tally. This code takes the "Susceptible.1" column
  # and summarises it by gene for your total Isolates pathogenic on each gene.
  # Likewise "Isolate_N" is calculated given the unique isolate names to find
  # the total number of isolates within your data set.
  # "Percent_isolates_pathogenic" is then found for each gene, showing the
  # percentage of isolates that are pathogenic on tested genes.
  # "Rps.Gene.Summary" will return these values.
  
  x <- .summarise_rps_genes(.x = x)
  x[, percent.pathogenic := round((N) / max(N) * 100, 2)]
  return(x)
}

#' Visualize _Rps_ Gene Summaries
#'
#' @description Creates a \pkg{ggplot2} object of the _Rps_ gene summaries
#'  calculated by [summarize_Rps()]
#' @param x A `data.frame` generated by [summarize_Rps()]. Character.
#'
#' @details
#' The `data.frame` object supplied should be generated by [summarize_Rps()] and
#'  contain the following fields.
#'
#'  * Rps - _Rps_ gene(s) included in study
#'  * N - Total number of plants susceptible
#'  * percent.pathogenic - Percent of isolates pathogenic on _Rps_ genes
#'
#' @examples
#  # locate system file for import
#' Ps <- system.file("extdata", "practice_data_set.csv", package = "hagis")
#'
#' # import 'practice_data_set.csv'
#' Ps <- read.csv(Ps)
#'
#' # calculate totals and percents for resistant and susceptible reactions
#' Ps <- calc_percents(Ps)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#' susc <- summarize_Rps(Ps, cutoff = 60)
#'
#' # Visualize the summary of _Rps_ genes
#' visualize_Rps(susc)
#'
#' @seealso [write_template()], [calc_percents()], [summarize_Rps()]
#' @export visualize_Rps

visualize_Rps <- function(x) {
  # CRAN NOTE avoidance
  Rps <- percent.pathogenic <- NULL
  
  susceptibilities_graph <-
    ggplot2::ggplot(data = x,
                    ggplot2::aes(x = Rps,
                                 y = percent.pathogenic)) +
    ggplot2::geom_col() +
    ggplot2::labs(y = "Percent of Isolates",
                  x = "") +
    ggplot2::ggtitle(expression("Percentage of Isolates Pathogenic on" ~
                                  italic(Rps) ~ "genes")) +
    ggplot2::coord_flip()
  return(susceptibilities_graph)
}
