
#' Calculate and Summarize Distribution of Susceptibilities by _Rps_ Gene
#'
#' @description This function will calculate the distribution of
#' susceptibilities by _Rps_ gene.
#' @param x a `data.frame` containing the data. Character.
#' @param cutoff value for percent susceptible cutoff. Numeric.
#' @param control value used to denote the susceptible control in the `Rps`
#'  field. Character.
#' @param sample field providing the unique isolate identification for each
#'  isolate being tested. Character.
#' @param Rps field providing the _Rps_ gene(s) being tested. Character.
#' @param perc_susc field providing the percent susceptible reactions.
#'  Character.
#'
#' @examples
#'
#' # locate system file for import
#' Ps <- system.file("extdata", "practice_data_set.csv", package = "hagis")
#'
#' # import 'practice_data_set.csv'
#' Ps <- read.csv(Ps)
#' head(Ps)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#' susc <- summarize_rps(x = Ps,
#'                        cutoff = 60,
#'                        control = "susceptible",
#'                        sample = "Isolate",
#'                        Rps = "Rps",
#'                        perc_susc = "perc.susc")
#' susc
#'
#' # plot susceptibilities
#' autoplot(susc)
#'
#' @return  returns an object of [class()] `hagis.rps.summary`
#' An object of class `hagis.summaries` is a [data.table][data.table()]
#'  containing the following components fields
#'   \describe{
#'     \item{Rps}{the Rps gene}
#'     \item{N_susc}{the total number susceptible for a given _Rps_ gene in the
#'      `Rps` field}
#'     \item{percent_pathogenic}{the frequency with which an _Rps_ gene is
#'     pathogenic}
#'   }
#' @importFrom data.table ":="
#' @export summarize_rps

summarize_rps <- function(x,
                          cutoff,
                          control,
                          sample,
                          Rps,
                          perc_susc) {

  .check_inputs(
    .x = x,
    .cutoff = cutoff,
    .control = control,
    .sample = sample,
    .Rps = Rps,
    .perc_susc = perc_susc
  )
  
  # CRAN NOTE avoidance
  cutoff <- percent_pathogenic <- N_susc <- NULL
  
  data.table::setDT(x)
  
  # summary by rps gene to tally. This code takes the "Susceptible.1" column
  # and summarizes it by gene for your total Isolates pathogenic on each gene.
  x <- .binary_cutoff(.x = x, .cutoff = cutoff)
  x <- .create_summary_rps(.y = x, .Rps = Rps)
  x[, percent_pathogenic := round((N_susc) / max(N_susc) * 100, 2)]
  
  # Set new class
  class(x) <- union("hagis.rps.summary", class(x))
  return(x)
}

#' Plot _Rps_ Gene Summaries
#'
#' @description Creates a \pkg{ggplot2} object of the _Rps_ gene
#'  summaries calculated by [summarize_rps()]
#' @param object a `hagis.rps.summary` object generated by [summarize_rps()].
#'  Character.
#' @param ... passed to the chosen `geom(s)`
#'
#' @examples
#  # locate system file for import
#' Ps <- system.file("extdata", "practice_data_set.csv", package = "hagis")
#'
#' # import 'practice_data_set.csv'
#' Ps <- read.csv(Ps)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#' susc <- summarize_rps(x = Ps,
#'                        cutoff = 60,
#'                        control = "susceptible",
#'                        sample = "Isolate",
#'                        Rps = "Rps",
#'                        perc_susc = "perc.susc")
#'
#' # Visualize the summary of Rps genes
#' plot(susc)
#' @method autoplot hagis.rps.summary
#' @return A \link[ggplot2]{ggplot2} plot
#' @export
#' @noRd

autoplot.hagis.rps.summary <- function(object, ...) {
  # CRAN NOTE avoidance
  Rps <- percent_pathogenic <- NULL
  ggplot2::ggplot(data = object,
                  ggplot2::aes(x = Rps,
                               y = percent_pathogenic)) +
    ggplot2::geom_col() +
    ggplot2::labs(y = "Percent of Isolates",
                  x = "") +
    ggplot2::ggtitle(expression("Percentage of Isolates Pathogenic on" ~
                                  italic(Rps) ~ "genes")) +
    ggplot2::coord_flip()
}

#' Create Summary Table of Binary Reactions by Rps Gene
#'
#' Tally a summary by pathogenicity gene. This code takes the "Susceptible.1"
#'  column and summarises it by gene for your total Isolates pathogenic on each
#'  Rps gene.
#'
#' @param .x a `data.table` containing the values to be summarised
#' @return A `data.table` that tallies the results by pathogenicity gene
#' @author Adam H. Sparks, adamhsparks@@gmail.com
#' @keywords Internal
#' @noRd
.create_summary_rps <- function(.y, .Rps) {
  expr = paste0(".y[, list(N_susc = sum(susceptible.1)), by = list(Rps = ",
                .Rps,
                ")]")
  y <- eval(parse(text = expr))
  return(y)
}
