
#' Calculate and Summarize Distribution of Susceptibilities by _Rps_ Gene
#'
#' @description This function will calculate the distribution of
#' susceptibilities by _Rps_ gene.
#' @param x A `data.frame` containing the data. Character.
#' @param cutoff Value for percent susceptible cutoff. Numeric.
#' @param control Value used to denote the susceptible control in the `Rps`
#'  field. Character.
#' @param sample Field providing the unique isolate identification for each
#'  isolate being tested. Character.
#' @param Rps Field providing the _Rps_ gene(s) being tested. Character.
#' @param perc_susc Field providing the percent susceptible reactions.
#'  Character.
#'
#' @examples
#'
#' # locate system file for import
#' Ps <- system.file("extdata", "practice_data_set.csv", package = "hagis")
#'
#' # import 'practice_data_set.csv'
#' Ps <- read.csv(Ps)
#' head(Ps)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#' susc <- summarize_rps(x = Ps,
#'                        cutoff = 60,
#'                        control = "susceptible",
#'                        sample = "Isolate",
#'                        Rps = "Rps",
#'                        perc_susc = "perc.susc")
#' susc
#'
#' @seealso [write_template()], [percents()], [visualize_rps()]
#' @importFrom data.table ":="
#' @export summarize_rps

summarize_rps <- function(x,
                           cutoff,
                           control,
                           sample,
                           Rps,
                           perc_susc) {
  # CRAN NOTE avoidance
  cutoff <- percent.pathogenic <- N_susc <- NULL
  
  if (missing(x) |
      missing(cutoff) |
      missing(control) |
      missing(sample) |
      missing(Rps) |
      missing(perc_susc)) {
    stop(call. = FALSE,
         "You have failed to provide all necessary inputs.\
         Please check and try again.")
  }
  
  data.table::setDT(x)
  
  # summary by rps gene to tally. This code takes the "Susceptible.1" column
  # and summarizes it by gene for your total Isolates pathogenic on each gene.
  x <- .binary_cutoff(.x = x, .cutoff = cutoff)
  x <- .create_summary_rps(.y = x, .Rps = Rps)
  x[, percent.pathogenic := round((N_susc) / max(N_susc) * 100, 2)]
  return(x)
}

#' Visualize _Rps_ Gene Summaries
#'
#' @description Creates a \pkg{ggplot2} object of the _Rps_ gene
#'  summaries calculated by [summarize_rps()]
#' @param x A `data.frame` generated by [summarize_rps()]. Character.
#'
#' @examples
#  # locate system file for import
#' Ps <- system.file("extdata", "practice_data_set.csv", package = "hagis")
#'
#' # import 'practice_data_set.csv'
#' Ps <- read.csv(Ps)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#' susc <- summarize_rps(x = Ps,
#'                        cutoff = 60,
#'                        control = "susceptible",
#'                        sample = "Isolate",
#'                        Rps = "Rps",
#'                        perc_susc = "perc.susc")
#'
#' # Visualize the summary of Rps genes
#' visualize_rps(susc)
#'
#' @seealso [summarize_rps()]
#' @export visualize_rps

visualize_rps <- function(x) {
  # CRAN NOTE avoidance
  Rps <- percent.pathogenic <- NULL
  
  susceptibilities_graph <-
    ggplot2::ggplot(data = x,
                    ggplot2::aes(x = Rps,
                                 y = percent.pathogenic)) +
    ggplot2::geom_col() +
    ggplot2::labs(y = "Percent of Isolates",
                  x = "") +
    ggplot2::ggtitle(expression("Percentage of Isolates Pathogenic on" ~
                                  italic(Rps) ~ "genes")) +
    ggplot2::coord_flip()
  return(susceptibilities_graph)
}

#' Create Summary Table of Binary Reactions by Rps Gene
#'
#' Tally a summary by pathogenicity gene. This code takes the "Susceptible.1"
#'  column and summarises it by gene for your total Isolates pathogenic on each
#'  Rps gene.
#'
#' @param .x A `data.table` containing the values to be summarised
#' @return A `data.table` that tallies the results by pathogenicity gene
#' @author Adam H. Sparks, adamhsparks@@gmail.com
#' @noRd
.create_summary_rps <- function(.y, .Rps) {
  expr = paste0(".y[, list(N_susc = sum(susceptible.1)), by = list(Rps = ",
                .Rps,
                ")]")
  y <- eval(parse(text = expr))
  return(y)
}
