


#' Calculate and Summarize Distribution of Susceptibilities by Pathogenicity Gene
#'
#' @description This function will calculate the distribution of
#' susceptibilities by pathogenicity gene.
#' @param x A `data.frame` containing the data. Character.
#' @param cutoff Value for percent susceptible cutoff. Numeric.
#' @param control Value used to denote the susceptible control in the `gene`
#'  field. Character.
#' @param sample Field providing the unique isolate identification for each
#'  isolate being tested. Character.
#' @param gene Field providing the pathogenicty gene(s) being tested. Character.
#' @param perc_susc Field providing the percent susceptible reactions.
#'  Character.
#'
#' @examples
#'
#' # locate system file for import
#' Ps <- system.file("extdata", "practice_data_set.csv", package = "hagis")
#'
#' # import 'practice_data_set.csv'
#' Ps <- read.csv(Ps)
#' head(Ps)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#' susc <- summarize_susc(x = Ps,
#'                        cutoff = 60,
#'                        control = "susceptible",
#'                        sample = "Isolate",
#'                        gene = "Rps",
#'                        perc_susc = "perc.susc")
#' susc
#'
#' @seealso [write_template()], [percents()], [visualize_susc()]
#' @importFrom data.table ":="
#' @export summarize_susc

summarize_susc <- function(x,
                           cutoff,
                           control,
                           sample,
                           gene,
                           perc_susc) {
  # CRAN NOTE avoidance
  cutoff <- percent.pathogenic <- NULL
  
  if (missing(x) |
      missing(cutoff) |
      missing(control) |
      missing(sample) |
      missing(gene) |
      missing(perc_susc)) {
    stop(call. = FALSE,
         "You have failed to provide all necessary inputs.\
         Please check and try again.")
  }
  
  data.table::setDT(x)
  
  # summary by rps gene to tally. This code takes the "Susceptible.1" column
  # and summarizes it by gene for your total Isolates pathogenic on each gene.
  # Likewise "Isolate_N" is calculated given the unique isolate names to find
  # the total number of isolates within your data set.
  # "Percent_isolates_pathogenic" is then found for each gene, showing the
  # percentage of isolates that are pathogenic on tested genes.
  # "Rps.Gene.Summary" will return these values.
  
  x <- .binary_cutoff(.x = x, .cutoff = cutoff)
  x <- .create_summary(.y = x, .gene = gene)
  x[, percent.pathogenic := round((N) / max(N) * 100, 2)]
  return(x)
}

#' Visualize Pathogenicity Gene Summaries
#'
#' @description Creates a \pkg{ggplot2} object of the pathogenicity gene
#'  summaries calculated by [summarize_susc()]
#' @param x A `data.frame` generated by [summarize_susc()]. Character.
#'
#' @examples
#  # locate system file for import
#' Ps <- system.file("extdata", "practice_data_set.csv", package = "hagis")
#'
#' # import 'practice_data_set.csv'
#' Ps <- read.csv(Ps)
#'
#' # calculate susceptibilities with a 60 % cutoff value
#' susc <- summarize_susc(x = Ps,
#'                        cutoff = 60,
#'                        control = "susceptible",
#'                        sample = "Isolate",
#'                        gene = "Rps",
#'                        perc_susc = "perc.susc")
#'
#' # Visualize the summary of pathogenicity genes
#' visualize_susc(susc)
#'
#' @seealso [write_template()], [calc_percents()], [summarize_susc()]
#' @export visualize_susc

visualize_susc <- function(x) {
  # CRAN NOTE avoidance
  gene <- percent.pathogenic <- NULL
  
  susceptibilities_graph <-
    ggplot2::ggplot(data = x,
                    ggplot2::aes(x = gene,
                                 y = percent.pathogenic)) +
    ggplot2::geom_col() +
    ggplot2::labs(y = "Percent of Isolates",
                  x = "") +
    ggplot2::ggtitle(expression("Percentage of Isolates Pathogenic on" ~
                                  italic(Rps) ~ "genes")) +
    ggplot2::coord_flip()
  return(susceptibilities_graph)
}
